HospitalProyecto/HospitalProyecto/Models/Medico.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HospitalProyecto.Models
{
    public class Medico : Persona
    {
        public int medicoID { get; set; }

        public String especialidad { get; set; }

        //Un medico puede estar en muchas citas//

        public virtual ICollection<Cita> citas { get; set; }
 


    }
}

HospitalProyecto/HospitalProyecto/Controllers/MedicoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HospitalProyecto.Models;
using HospitalProyecto.DAL;

namespace HospitalProyecto.Controllers
{
    public class MedicoController : Controller
    {
        private Contexto db = new Contexto();

        // GET: /Medico/
        public ActionResult Index()
        {
            return View(db.medicos.ToList());
        }

        // GET: /Medico/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Medico medico = db.medicos.Find(id);
            if (medico == null)
            {
                return HttpNotFound();
            }
            return View(medico);
        }

        // GET: /Medico/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Medico/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="medicoID,especialidad,nombre,apellidoP,apellidoM,telefono,direccion")] Medico medico)
        {
            if (ModelState.IsValid)
            {
                db.medicos.Add(medico);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(medico);
        }

        // GET: /Medico/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Medico medico = db.medicos.Find(id);
            if (medico == null)
            {
                return HttpNotFound();
            }
            return View(medico);
        }

        // POST: /Medico/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="medicoID,especialidad,nombre,apellidoP,apellidoM,telefono,direccion")] Medico medico)
        {
            if (ModelState.IsValid)
            {
                db.Entry(medico).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(medico);
        }

        // GET: /Medico/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Medico medico = db.medicos.Find(id);
            if (medico == null)
            {
                return HttpNotFound();
            }
            return View(medico);
        }

        // POST: /Medico/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Medico medico = db.medicos.Find(id);
            db.medicos.Remove(medico);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HospitalProyecto/HospitalProyecto/Views/Medico/Create.cshtml
@model HospitalProyecto.Models.Medico

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Medico</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.especialidad, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.especialidad)
                @Html.ValidationMessageFor(model => model.especialidad)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nombre, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombre)
                @Html.ValidationMessageFor(model => model.nombre)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.apellidoP, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.apellidoP)
                @Html.ValidationMessageFor(model => model.apellidoP)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.apellidoM, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.apellidoM)
                @Html.ValidationMessageFor(model => model.apellidoM)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.telefono, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.telefono)
                @Html.ValidationMessageFor(model => model.telefono)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.direccion, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.direccion)
                @Html.ValidationMessageFor(model => model.direccion)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HospitalProyecto/HospitalProyecto/Views/Medico/Delete.cshtml
@model HospitalProyecto.Models.Medico

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Medico</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.especialidad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.especialidad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.apellidoP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.apellidoP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.apellidoM)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.apellidoM)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.telefono)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.telefono)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.direccion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.direccion)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

HospitalProyecto/HospitalProyecto/Views/Medico/Details.cshtml
@model HospitalProyecto.Models.Medico

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Medico</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.especialidad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.especialidad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.apellidoP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.apellidoP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.apellidoM)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.apellidoM)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.telefono)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.telefono)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.direccion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.direccion)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.medicoID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

HospitalProyecto/HospitalProyecto/Views/Medico/Edit.cshtml
@model HospitalProyecto.Models.Medico
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="myModalLabel">Edit Person</h4>
</div>
@*@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}*@

@*<h2>Edit</h2>*@


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="modal-body">
        <div class="form-horizontal">
            <h4>Medico</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.medicoID)

            <div class="form-group">
                @Html.LabelFor(model => model.especialidad, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.especialidad)
                    @Html.ValidationMessageFor(model => model.especialidad)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.nombre, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.nombre)
                    @Html.ValidationMessageFor(model => model.nombre)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.apellidoP, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.apellidoP)
                    @Html.ValidationMessageFor(model => model.apellidoP)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.apellidoM, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.apellidoM)
                    @Html.ValidationMessageFor(model => model.apellidoM)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.telefono, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.telefono)
                    @Html.ValidationMessageFor(model => model.telefono)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.direccion, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.direccion)
                    @Html.ValidationMessageFor(model => model.direccion)
                </div>
            </div>
            </div>
        </div>
    
            <div class="modal-footer">
                <button class="btn" data-dismiss="modal">Cancel</button>
                <input class="btn btn-primary" type="submit" value="Save" />
            </div>
}

        @*<div>
            @Html.ActionLink("Back to List", "Index")
        </div>

        @section Scripts {
            @Scripts.Render("~/bundles/jqueryval")
        }*@

HospitalProyecto/HospitalProyecto/Views/Medico/Index.cshtml
@model IEnumerable<HospitalProyecto.Models.Medico>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id='myModal' class='modal fade in'>
    <div class="modal-dialog">
        <div class="modal-content">
            <div id='myModalContent'></div>
        </div>
    </div>
</div>

<div class="panel panel-primary">
    <div class="panel-heading"> Lista de Medicos</div>

    <div class="panel-body ">
        @Html.ActionLink("Add", "Create", "Medico", null, new { data_modal = "", id = "btnCreate", @class = "btn btn-small btn-primary pull-right" })
    </div>
    @*<h2>Medicos</h2>*@

    @*<p>
        @Html.ActionLink("Create New", "Create")
    </p>*@
    <table class="table table-bordered table-hover">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.especialidad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.apellidoP)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.apellidoM)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.telefono)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.direccion)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.especialidad)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.apellidoP)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.apellidoM)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.telefono)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.direccion)
                </td>
                <td>
                    <a id="enlaceDetalles" data-toggle="modal" data-target="#modalDetalles" nomatricula="@item.medicoID">Detalles</a> |
                    <a id="enlaceBorrar" data-toggle="modal" data-target="#modalBorrar" nomatricula="@item.medicoID">Borrar</a> |
                    <a id="enlaceEditar" data-toggle="modal" data-target="#modalEditar" nomatricula="@item.medicoID">Editar</a>
                </td>
                @*<td style="width:20px">
                    <div class="btn-group">
                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true">
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("Details", "Details", new { id = item.medicoID}, new { data_modal = "" })</li>
                            <li>@Html.ActionLink("Edit", "Edit", new { id = item.medicoID }, new { data_modal = "" })</li>
                            <li class="divider"></li>
                            <li>@Html.ActionLink("Delete", "Delete", new { id = item.medicoID }, new { data_modal = "" })</li>

                        </ul>
                    </div>
                </td>*@
            </tr>
        }
    </table>

    <div id="modalDetalles" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Detalles</h4>
                </div>
                <div class="modal-body">
                    <!-- VISTA DE DETALLES DE ALUMNO-->
                    @*Html.Partial("Details", vmAlumno)*@
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

    <div id="modalBorrar" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Eliminar</h4>
                </div>
                <div class="modal-body">
                    @*Html.Partial("Delete", vmAlumno)*@
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

    <div id="modalEditar" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Modificar</h4>
                </div>
                <div class="modal-body">
                    @*@Html.Partial("Edit", nuevoAlumno)*@
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="~/Scripts/modalform.js"></script>