HospitalProyecto/HospitalProyecto/Models/Cita.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HospitalProyecto.Models
{
    public class Cita
    {
        public int citaID { get; set; }

        public String descripcion { get; set; }

        public DateTime fecha { get; set; }
        //llave foranea de  cliente
        public int pacienteID { get; set; }
        public virtual Paciente paciente { get; set; }

        //llave foranea de  cliente
        public int medicoID { get; set; }
        public virtual Medico medico { get; set; }
    }
}

HospitalProyecto/HospitalProyecto/Controllers/CitaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HospitalProyecto.Models;
using HospitalProyecto.DAL;

namespace HospitalProyecto.Controllers
{
    public class CitaController : Controller
    {
        private Contexto db = new Contexto();

        // GET: /Cita/
        public ActionResult Index()
        {
            var citas = db.citas.Include(c => c.medico).Include(c => c.paciente);

            return View(citas.ToList());
        }

        // GET: /Cita/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cita cita = db.citas.Find(id);
            if (cita == null)
            {
                return HttpNotFound();
            }
            return View(cita);
        }

        // GET: /Cita/Create
        public ActionResult Create()
        {
            ViewBag.medicoID = new SelectList(db.medicos, "medicoID", "nombre");
            ViewBag.pacienteID = new SelectList(db.pacientes, "pacienteID", "nombre");
            return View();
        }

        // POST: /Cita/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="citaID,descripcion,fecha,pacienteID,medicoID")] Cita cita)
        {
            if (ModelState.IsValid)
            {
                db.citas.Add(cita);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.medicoID = new SelectList(db.medicos, "medicoID", "nombre", cita.medicoID);
            ViewBag.pacienteID = new SelectList(db.pacientes, "pacienteID", "nombre", cita.pacienteID);
            return View(cita);
        }

        // GET: /Cita/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cita cita = db.citas.Find(id);
            if (cita == null)
            {
                return HttpNotFound();
            }
            ViewBag.medicoID = new SelectList(db.medicos, "medicoID", "nombre", cita.medicoID);
            ViewBag.pacienteID = new SelectList(db.pacientes, "pacienteID", "nombre", cita.pacienteID);
            return View(cita);
        }

        // POST: /Cita/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="citaID,descripcion,fecha,pacienteID,medicoID")] Cita cita)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cita).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.medicoID = new SelectList(db.medicos, "medicoID", "nombre", cita.medicoID);
            ViewBag.pacienteID = new SelectList(db.pacientes, "pacienteID", "nombre", cita.pacienteID);
            return View(cita);
        }

        // GET: /Cita/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cita cita = db.citas.Find(id);
            if (cita == null)
            {
                return HttpNotFound();
            }
            return View(cita);
        }

        // POST: /Cita/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Cita cita = db.citas.Find(id);
            db.citas.Remove(cita);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HospitalProyecto/HospitalProyecto/Views/Cita/Create.cshtml
@model HospitalProyecto.Models.Cita

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Cita</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.descripcion, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.descripcion)
                @Html.ValidationMessageFor(model => model.descripcion)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.fecha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fecha, new { htmlAttributes = new { type = "date" } })
                @Html.ValidationMessageFor(model => model.fecha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.pacienteID, "pacienteID", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("pacienteID", String.Empty)
                @Html.ValidationMessageFor(model => model.pacienteID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.medicoID, "medicoID", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("medicoID", String.Empty)
                @Html.ValidationMessageFor(model => model.medicoID)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HospitalProyecto/HospitalProyecto/Views/Cita/Delete.cshtml
@model HospitalProyecto.Models.Cita

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Cita</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.medico.especialidad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.medico.especialidad)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.medico.fecha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.medico.fecha)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.paciente.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.paciente.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.descripcion)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

HospitalProyecto/HospitalProyecto/Views/Cita/Details.cshtml
@model HospitalProyecto.Models.Cita

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Cita</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.medico.especialidad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.medico.especialidad)
        </dd>
        <dd>
            @Html.DisplayNameFor(model => model.medico.fecha)
        </dd>
        <dd>
            @Html.DisplayFor(model => model.medico.fecha)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.paciente.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.paciente.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.descripcion)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.citaID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

HospitalProyecto/HospitalProyecto/Views/Cita/Edit.cshtml
@model HospitalProyecto.Models.Cita

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Cita</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.citaID)

        <div class="form-group">
            @Html.LabelFor(model => model.descripcion, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.descripcion)
                @Html.ValidationMessageFor(model => model.descripcion)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.fecha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fecha, new { htmlAttributes = new { @class = "form-control"} })
                
                @Html.ValidationMessageFor(model => model.fecha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.pacienteID, "pacienteID", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("pacienteID", String.Empty)
                @Html.ValidationMessageFor(model => model.pacienteID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.medicoID, "medicoID", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("medicoID", String.Empty)
                @Html.ValidationMessageFor(model => model.medicoID)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HospitalProyecto/HospitalProyecto/Views/Cita/Index.cshtml
@model IEnumerable<HospitalProyecto.Models.Cita>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div id='myModal' class='modal fade in'>
    <div class="modal-dialog">
        <div class="modal-content">
            <div id='myModalContent'></div>
        </div>
    </div>
</div>

<div class="panel panel-primary">
    <div class="panel-heading"> Lista de Citas</div>

    <div class="panel-body ">
        @Html.ActionLink("Add", "Create", "Cita", null, new { data_modal = "", id = "btnCreate", @class = "btn btn-small btn-primary pull-right" })
    </div>
    @*<h2>Citas</h2>*@

    @*<p>
            @Html.ActionLink("Create New", "Create")
        </p>*@
    <table class="table table-bordered table-hover">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.medico.nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.paciente.nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.descripcion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.fecha)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.medico.nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.paciente.nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.descripcion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.fecha)
                </td>
                <td>
                    <a id="enlaceDetalles" data-toggle="modal" data-target="#modalDetalles" nomatricula="@item.citaID">Detalles</a> |
                    <a id="enlaceBorrar" data-toggle="modal" data-target="#modalBorrar" nomatricula="@item.citaID">Borrar</a> |
                    <a id="enlaceEditar" data-toggle="modal" data-target="#modalEditar" nomatricula="@item.citaID">Editar</a>
                </td>
                @*<td style="width:20px">
                        <div class="btn-group">
                            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true">
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu" role="menu">
                                <li>@Html.ActionLink("Details", "Details", new { id = item.citaID }, new { data_modal = "" })</li>
                                <li>@Html.ActionLink("Edit", "Edit", new { id = item.citaID }, new { data_modal = "" })</li>
                                <li class="divider"></li>
                                <li>@Html.ActionLink("Delete", "Delete", new { id = item.citaID }, new { data_modal = "" })</li>

                            </ul>
                        </div>
                    </td>*@
            </tr>
        }
    </table>

    <div id="modalDetalles" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Detalles</h4>
                </div>
                <div class="modal-body">
                    <!-- VISTA DE DETALLES DE ALUMNO-->
                    @*Html.Partial("Details", vmAlumno)*@
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

    <div id="modalBorrar" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Eliminar</h4>
                </div>
                <div class="modal-body">
                    @*Html.Partial("Delete", vmAlumno)*@
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

    <div id="modalEditar" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Modificar</h4>
                </div>
                <div class="modal-body">
                    @*@Html.Partial("Edit", nuevoAlumno)*@
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
<script src="~/Scripts/modalform.js"></script>