HospitalProyecto/HospitalProyecto/Models/Paciente.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace HospitalProyecto.Models
{
    public class Paciente : Persona
    {
        public int pacienteID { get; set; }


        //Un paciente puede estar en muchas  citas//
        public virtual ICollection<Cita> citas { get; set; }

    }
        /*Representa la definicion de un modelo para vista (ViewModel),
     * por lo que no contiene información de relaciones con otras entidades*/
    public class VMPaciente
    {
        public int pacienteID { get; set; }
       [DisplayName("Nombre")]
        public String nombre { get; set; }
        [DisplayName("Apellido Paterno")]
        public String apellidoP { get; set; }
        [DisplayName("Apellido Materno")]
        public String apellidoM { get; set; }
        [DisplayName("Telefono")]
        public String telefono { get; set; }
        [DisplayName("Direccion")]
        public String direccion { get; set; }


        public VMPaciente(Paciente paciente)
        {
            this.pacienteID = paciente.pacienteID;
            this.nombre = paciente.nombre;
            this.apellidoP = paciente.apellidoP;
            this.apellidoM = paciente.apellidoM;
            this.telefono = paciente.telefono;
            this.direccion = paciente.direccion;



        }
    }
}

HospitalProyecto/HospitalProyecto/Controllers/PacienteController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HospitalProyecto.Models;
using HospitalProyecto.DAL;
using System.Web.Script.Serialization;

namespace HospitalProyecto.Controllers
{
    public class PacienteController : Controller
    {
        private Contexto db = new Contexto();


        public ActionResult PruebaAjax()
        {
            return View();
        }

        public JsonResult EntregarDatos()
        {
            //var listaJson = from alumno in 
            //return Json(db.carreras.ToList(),JsonRequestBehavior.AllowGet);
            JavaScriptSerializer jss = new JavaScriptSerializer();
            String dato = "Esto viene del server";
            return Json(jss.Serialize(dato), JsonRequestBehavior.AllowGet);
        }

        // GET: /Paciente/
        public ActionResult Index()
        {
            return View(db.pacientes.ToList());
        }

        public JsonResult AjaxIndex(String nada)
        {
            //var alumnos = db.alumnos.ToList();

            var varpacientes = from Paciente in db.pacientes
                         
                         select new
                         {
                             pacienteID = Paciente.pacienteID,
                             nombre = Paciente.nombre,
                             apellidoP = Paciente.apellidoP,
                             apellidoM = Paciente.apellidoM,
                             telefono = Paciente.telefono,
                             direccion = Paciente.direccion
                         };

            return Json(varpacientes, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult CreateAjax(Paciente paciente)
        {

            String mensaje = String.Empty;

            try
            {
                if (ModelState.IsValid)
                {
                    db.pacientes.Add(paciente);
                    db.SaveChanges();



                    mensaje = "Registro guardado";
                }
            }
            catch (Exception exc)
            {
                mensaje = "maldito servido FUCK YOU!: " + exc.Message;
            }
            return Json(new { mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

        
        // GET: /Paciente/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Paciente paciente = db.pacientes.Find(id);
            if (paciente == null)
            {
                return HttpNotFound();
            }
            return View(paciente);
        }
        // GET: Alumno/Details/5
        //[Authorize(Roles = "Administrador, Capturista")]
      [HttpGet]
        public JsonResult AjaxDetails(int? id)
        {
            Paciente paciente = db.pacientes.Find(id);
            VMPaciente vmPaciente = new VMPaciente(paciente);

            return Json(vmPaciente, JsonRequestBehavior.AllowGet);
        }

        // GET: /Paciente/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Paciente/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="pacienteID,nombre,apellidoP,apellidoM,telefono,direccion")] Paciente paciente)
        {
            if (ModelState.IsValid)
            {
                db.pacientes.Add(paciente);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(paciente);
        }

        // GET: /Paciente/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Paciente paciente = db.pacientes.Find(id);
            if (paciente == null)
            {
                return HttpNotFound();
            }
            return View(paciente);
        }

        // POST: /Paciente/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="pacienteID,nombre,apellidoP,apellidoM,telefono,direccion")] Paciente paciente)
        {
            if (ModelState.IsValid)
            {
                db.Entry(paciente).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(paciente);
        }

        // GET: /Paciente/Delete/5
        [HttpGet]
        public JsonResult DeleteConfirmed(int idpaciente = 0)
        {
            String mensaje = "";
            try
            {
                Paciente paciente = db.pacientes.Find(idpaciente);
                db.pacientes.Remove(paciente);
                db.SaveChanges();
                mensaje = " Todo salio Muy Bien";
            }
            catch
            {
                mensaje = "Hubo un error";
            }
            return Json(new { mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

        // POST: /Paciente/Delete/5
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public JsonResult Delete(int idpaciente = 0)
        {
            Paciente paciente = db.pacientes.Find(idpaciente);
            db.pacientes.Remove(paciente);
            db.SaveChanges();
            return Json(paciente, JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        [HttpGet]
        public JsonResult AjaxEdit(int pacienteID = 0)
        {
            /*Un objeto instanciado del modelo de datos*/
            Paciente paciente = db.pacientes.Find(pacienteID);

            /*Necesito una instancia del modelo de vista*/
            VMPaciente vmPaciente = new VMPaciente(paciente);

            return Json(vmPaciente, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult AjaxEdit(Paciente paciente)
        {
            String mensaje = String.Empty;

            try
            {
                db.Entry(paciente).State = EntityState.Modified;
                int c = db.SaveChanges();
                mensaje = "Se ha editado los datos del alumno satisfactoriamente";
            }
            catch (Exception exc)
            {
                mensaje = "Hubo un error en el servidor: " + exc.Message;
            }


            return Json(new { mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

    }
}

HospitalProyecto/HospitalProyecto/Views/Paciente/Create.cshtml
@model HospitalProyecto.Models.Paciente

@{
    ViewBag.Title = "Create";
    //Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Paciente</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.nombre, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombre)
                @Html.ValidationMessageFor(model => model.nombre)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.apellidoP, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.apellidoP)
                @Html.ValidationMessageFor(model => model.apellidoP)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.apellidoM, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.apellidoM)
                @Html.ValidationMessageFor(model => model.apellidoM)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.telefono, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.telefono)
                @Html.ValidationMessageFor(model => model.telefono)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.direccion, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.direccion)
                @Html.ValidationMessageFor(model => model.direccion)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button id="btnCrearPacientes">Registrame</button>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HospitalProyecto/HospitalProyecto/Views/Paciente/Delete.cshtml
@model HospitalProyecto.Models.Paciente

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Paciente</h4>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            @*<input id="DeletePaciente" type="submit" value="Delete" class="btn btn-default" /> |*@
            <button id="DeletePaciente">Borrar</button>
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

HospitalProyecto/HospitalProyecto/Views/Paciente/Details.cshtml
@model HospitalProyecto.Models.VMPaciente

@{
    ViewBag.Title = "Details";
    //Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Paciente</h4>
	<hr />
    <dl id="DetallesPaciente" class="dl-horizontal">
        @Html.HiddenFor(model => model.pacienteID)
        <dt>
            @Html.DisplayNameFor(model => model.nombre)
        </dt>

        <dd id="nombre">
            @Html.DisplayFor(model => model.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.apellidoP)
        </dt>

        <dd id="@Html.DisplayNameFor(model => model.apellidoP)">
            @Html.DisplayFor(model => model.apellidoP)
        </dd>

        <dt >
            @Html.DisplayNameFor(model => model.apellidoM)
        </dt>

        <dd id="@Html.DisplayNameFor(model => model.apellidoM)">
            @Html.DisplayFor(model => model.apellidoM)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.telefono)
        </dt>

        <dd id="@Html.DisplayNameFor(model => model.telefono)">
            @Html.DisplayFor(model => model.telefono)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.direccion)
        </dt>

        <dd id="@Html.DisplayNameFor(model => model.direccion)">
            @Html.DisplayFor(model => model.direccion)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.pacienteID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

HospitalProyecto/HospitalProyecto/Views/Paciente/Edit.cshtml
@model HospitalProyecto.Models.Paciente

@{
    ViewBag.Title = "Edit";
    //Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit","Paciente",FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Paciente</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.pacienteID)

        <div class="form-group">
            @Html.LabelFor(model => model.nombre, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombre)
                @Html.ValidationMessageFor(model => model.nombre)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.apellidoP, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.apellidoP)
                @Html.ValidationMessageFor(model => model.apellidoP)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.apellidoM, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.apellidoM)
                @Html.ValidationMessageFor(model => model.apellidoM)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.telefono, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.telefono)
                @Html.ValidationMessageFor(model => model.telefono)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.direccion, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.direccion)
                @Html.ValidationMessageFor(model => model.direccion)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HospitalProyecto/HospitalProyecto/Views/Paciente/Index.cshtml
@model IEnumerable<HospitalProyecto.Models.Paciente>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    HospitalProyecto.Models.Paciente nuevoPaciente = new HospitalProyecto.Models.Paciente();
    HospitalProyecto.Models.VMPaciente vmPaciente = new HospitalProyecto.Models.VMPaciente(nuevoPaciente);

}

                   
 @*modal placeholder
<div id='myModal' class='modal fade in'>
    <div class="modal-dialog">
        <div class="modal-content">
            <div id='myModalContent'></div>
        </div>
    </div>
</div>*@

<div class="panel panel-primary">
    <div class="panel-heading"> Lista de Pacientes</div>

    <div class="panel-body ">
        @*<button id="#modalPaciente" class="btn btn-small btn-primary pull-right">Add</button>*@
        <button type="button" class="btn btn-success" data-toggle="modal" data-target="#modalPaciente" style="margin-top: 10px">Add</button>
    </div>

    @*<h2>Pacientes</h2>*@
    @*<button id="botonPrueba">Boton Nuevo</button>*@
    @*<p>
        @Html.ActionLink("Create New", "Create")
        </p>*@
    <table id="tablaPaciente" class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.pacienteID)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.nombre)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.apellidoP)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.apellidoM)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.telefono)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.direccion)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    @*@Html.RadioButton("seleccion", item.pacienteID)*@
                    <td>
                        @Html.DisplayFor(modelItem => item.pacienteID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.nombre)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.apellidoP)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.apellidoM)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.telefono)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.direccion)
                    </td>
                    <td>

                        <a id="enlaceDetalles" data-toggle="modal" data-target="#modalDetalles" pacienteid="@item.pacienteID">Details</a> |
                        <a id="enlaceBorrar" data-toggle="modal" data-target="#modalBorrar" pacienteid="@item.pacienteID">Delete</a> |
                        <a id="enlaceEditar" data-toggle="modal" data-target="#modalEditar" pacienteid="@item.pacienteID">Edit</a>
                    </td>

                </tr>
            }
        </tbody>
    </table>
    <div id="modalDetalles" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Detalles</h4>
                </div>
                <div class="modal-body">
                    <!-- VISTA DE DETALLES DE ALUMNO-->
                    @Html.Partial("Details", vmPaciente);
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="modalBorrar" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Eliminar</h4>
            </div>
            <div class="modal-body">
                @Html.Partial("Delete", nuevoPaciente)
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<div id="modalEditar" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Modificar</h4>
            </div>
            <div class="modal-body">
                @Html.Partial("Edit", nuevoPaciente)
            </div>
            <div class="modal-footer">
                
                <button id="botonBorrar" type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<div id="modalPaciente" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <div class="modal-content">
            <div class="modal-header">

                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Registrando ando </h4>
            </div>

            <div class="modal-body">
                @Html.Partial("Create", nuevoPaciente)
              
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Salir</button>
            </div>


        </div>
    </div>
</div>

<script src="~/Scripts/modalform.js"></script>